"""Dev tool: convert ./groebner/testcases/* into groebner_corpus.py.

Run manually from a checkout that has the sibling ./groebner repo:
    python symengine/tests/_gen_corpus.py /path/to/groebner/testcases
    python symengine/tests/_gen_corpus.py --dry-run /path/to/groebner/testcases
    python symengine/tests/_gen_corpus.py --force /path/to/groebner/testcases

Not used by CI -- the generated groebner_corpus.py is committed instead.

By default (no --force), the generator preserves existing golden_size and
golden_gfp metadata from the current groebner_corpus.py.  Use --force to
discard all existing metadata (fresh start).
"""
import sys, os, pprint, argparse

# Curated subset: small/medium, parseable, with known golden sizes filled in
# from a verified engine (see Step 3.3 of 08-IMPROVE-PHASE01.md).
# Excludes systems that use parentheses/rational coefficients (filter9, jcf26)
# and systems that are too slow for unit tests (katsura7+, lichtblau).
CURATED = [
    "cyclic3", "cyclic4", "cyclic5",
    "rose", "Uteshev_Bikker", "liu",
]

GOLDEN_KEYS = ("golden_size", "golden_gfp")


def parse(path):
    with open(path) as f:
        lines = [ln.strip() for ln in f if ln.strip()]
    gens = lines[0].split(",")
    polys = [p.replace("^", "**") for p in lines[1].split(",")]
    return gens, polys


def load_existing():
    """Import the current groebner_corpus.py and return the SYSTEMS dict.

    Returns an empty dict if the file does not exist or cannot be imported.
    """
    corpus_path = os.path.join(os.path.dirname(__file__), "groebner_corpus.py")
    if not os.path.exists(corpus_path):
        return {}
    # Import the corpus module without polluting sys.modules permanently.
    import importlib.util
    spec = importlib.util.spec_from_file_location("_existing_corpus", corpus_path)
    mod = importlib.util.module_from_spec(spec)
    try:
        spec.loader.exec_module(mod)
    except Exception:
        return {}
    return getattr(mod, "SYSTEMS", {})


def merge_entry(new_entry, existing_entry):
    """Merge golden metadata from *existing_entry* into *new_entry*.

    Only copies keys listed in GOLDEN_KEYS when they are absent from *new_entry*.
    Returns a new dict (does not mutate *new_entry*).
    """
    merged = dict(new_entry)
    for key in GOLDEN_KEYS:
        if key not in merged and key in existing_entry:
            merged[key] = existing_entry[key]
    return merged


def main(tcdir, force=False, dry_run=False):
    existing = {} if force else load_existing()

    out = {}
    added, preserved, skipped = [], [], []
    for name in CURATED:
        p = os.path.join(tcdir, name)
        if not os.path.exists(p):
            skipped.append(name)
            continue
        gens, polys = parse(p)
        entry = {"gens": gens, "polys": polys}
        if name in existing:
            entry = merge_entry(entry, existing[name])
            preserved.append(name)
        else:
            added.append(name)
        out[name] = entry

    # Report
    print(f"Preserved metadata: {preserved or '(none)'}")
    print(f"New systems (no golden data): {added or '(none)'}")
    print(f"Skipped (missing): {skipped or '(none)'}")

    corpus_path = os.path.join(os.path.dirname(__file__), "groebner_corpus.py")
    if dry_run:
        print(f"\n[DRY RUN] Would write {corpus_path} with {len(out)} systems.")
        return

    with open(corpus_path, "w") as f:
        f.write('"""Vendored Groebner benchmark systems (from the groebner '
                'testcase corpus). Auto-generated by _gen_corpus.py; do not '
                'edit by hand. golden_size filled in by hand from a verified '
                'engine."""\n\n')
        f.write("SYSTEMS = ")
        f.write(pprint.pformat(out, width=100, sort_dicts=True))
        f.write("\n")
    print(f"\nWrote {corpus_path} with {len(out)} systems.")


if __name__ == "__main__":
    ap = argparse.ArgumentParser(description=__doc__,
                                 formatter_class=argparse.RawDescriptionHelpFormatter)
    ap.add_argument("tcdir", nargs="?",
                    default=os.path.join(os.path.dirname(__file__),
                                         "../../../groebner/testcases"),
                    help="Path to groebner/testcases directory")
    ap.add_argument("--force", action="store_true",
                    help="Discard existing golden metadata (fresh start)")
    ap.add_argument("--dry-run", action="store_true",
                    help="Show what would change without writing")
    args = ap.parse_args()
    main(args.tcdir, force=args.force, dry_run=args.dry_run)
