"""Dev tool: convert ./groebner/testcases/* into groebner_corpus.py.

Run manually from a checkout that has the sibling ./groebner repo:
    python symengine/tests/_gen_corpus.py /path/to/groebner/testcases
Not used by CI -- the generated groebner_corpus.py is committed instead.
"""
import sys, os, pprint

# Curated subset: small/medium, parseable, with known golden sizes filled in
# from a verified engine (see Step 3.3 of 08-IMPROVE-PHASE01.md).
# Excludes systems that use parentheses/rational coefficients (filter9, jcf26)
# and systems that are too slow for unit tests (katsura7+, lichtblau).
CURATED = [
    "cyclic3", "cyclic4", "cyclic5",
    "rose", "Uteshev_Bikker", "liu",
]

def parse(path):
    with open(path) as f:
        lines = [ln.strip() for ln in f if ln.strip()]
    gens = lines[0].split(",")
    polys = [p.replace("^", "**") for p in lines[1].split(",")]
    return gens, polys

def main(tcdir):
    out = {}
    for name in CURATED:
        p = os.path.join(tcdir, name)
        if not os.path.exists(p):
            print("skip (missing):", name); continue
        gens, polys = parse(p)
        out[name] = {"gens": gens, "polys": polys}
    with open(os.path.join(os.path.dirname(__file__), "groebner_corpus.py"), "w") as f:
        f.write('"""Vendored Groebner benchmark systems (from the groebner '
                'testcase corpus). Auto-generated by _gen_corpus.py; do not '
                'edit by hand. golden_size filled in by hand from a verified '
                'engine."""\n\n')
        f.write("SYSTEMS = ")
        f.write(pprint.pformat(out, width=100, sort_dicts=True))
        f.write("\n")

if __name__ == "__main__":
    main(sys.argv[1] if len(sys.argv) > 1 else
         os.path.join(os.path.dirname(__file__), "../../../groebner/testcases"))
