"""Vendored Groebner benchmark systems (from the groebner testcase corpus).
Auto-generated by _gen_corpus.py; do not edit by hand. golden_size filled in
by hand from a verified engine (f5b, degrevlex, confirmed with buchberger).
"""

SYSTEMS = {
    'cyclic3': {
        'gens': ['a', 'b', 'c'],
        'polys': ['a+b+c', 'a*b+a*c+b*c', 'a*b*c-1'],
        'golden_size': 3,
    },
    'cyclic4': {
        'gens': ['a', 'b', 'c', 'd'],
        'polys': ['a+b+c+d', 'a*b+b*c+a*d+c*d',
                  'a*b*c+a*b*d+a*c*d+b*c*d', 'a*b*c*d-1'],
        'golden_size': 7,
    },
    'cyclic5': {
        'gens': ['a', 'b', 'c', 'd', 'e'],
        'polys': ['a*b*c*d*e-1',
                  'a*b*c*d+a*b*c*e+a*b*d*e+a*c*d*e+b*c*d*e',
                  'a*b*c+a*b*e+a*d*e+b*c*d+c*d*e',
                  'a*b+a*e+b*c+c*d+d*e',
                  'a+b+c+d+e'],
        'golden_size': 20,
    },
    'rose': {
        'gens': ['z', 'y', 'x'],
        'polys': [
            '7*y**4-20*x**2',
            '2160*z**4*x**2+1512*z**4*x+315*z**4-4000*x**2-2800*x-490',
            '67200000*y**3*x**5+94080000*y**3*x**4+40924800*y**3*x**3'
            '+2634240*y**3*x**2-2300844*y**3*x-432180*y**3'
            '+40320000*z*y**2*x**6+28800000*z*y**2*x**5'
            '+21168000*z*y**2*x**3+4939200*z*y**2*x**2+347508*z*y**2*x'
            '-23520000*z**2*y*x**4-41395200*z**2*y*x**3'
            '-26726560*z**2*y*x**2-7727104*z**2*y*x-852355*z**2*y'
            '-10080000*z**3*x**4-28224000*z**3*x**3-15288000*z**3*x**2'
            '-1978032*z**3*x-180075*z**3',
        ],
        'golden_size': 19,
    },
    'Uteshev_Bikker': {
        'gens': ['x', 'y', 'z', 't'],
        'polys': [
            'x**2+x*y+y**2-2*x*z-4*y*z+3*z**2-3*x*t+2*y*t+t**2'
            '-3*x-2*y+3*z-2*t-2',
            '2*x**2-x*y+y**2-x*z-y*z-6*z**2-x*t+y*t-5*z*t-3*t**2'
            '-5*x+y+5*z+2*t+5',
            '-3-3*x*y+2*x*z+x*t**2-5*x*z**2-5*z**2*t-3*x*t-2*z*t'
            '+x*y*z+x*y*t-x**2*z+x**2-y**2+2*z**2+11*z-2*t-x+y'
            '+x**3+y**3-3*z**3+2*t**3-3*t**2-5*y**2*z+7*y*z**2',
            '-15+2*x*y+11*x*t**2+5*x*z**2-z*t-4*x*y*z+6*x*y*t'
            '-x**2*z+3*x**2+2*y**2-z**2+4*z-10*t-35*x-14*y-x**3'
            '+6*y**3+15*z**3+4*t**3+5*t**2+6*y**2*z+4*y*z**2-x*z*t'
            '+6*x**2*y-12*x*y**2-7*y**2*t+2*y*t',
        ],
        'golden_size': 17,
    },
    'liu': {
        'gens': ['x', 'y', 'z', 't', 'a', 'h'],
        'polys': [
            'y*z-y*t-x*h+a*h',
            'z*t-z*x-y*h+a*h',
            't*x-y*t-z*h+a*h',
            'x*y-z*x-t*h+a*h',
        ],
        'golden_size': 12,
    },
}
